FROM node:14-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

# Starts nhinx server using nginx
# -g daemon off allows docker to track the process
# Prevents image from shuttng down as soon as it starts
CMD ["nginx", "-g", "daemon off;"]



